version: '3'
volumes:
  svn_data: {}
services:
  svn:
    image: garethflowers/svn-server:latest
    volumes:
      - svn_data:/var/opt/svn
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:3690:3690"
