name: Tests

on: [push]

jobs:

  test_svn_externals:
    # https://github.com/fiedl/icecube-git-migration/issues/2

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Create project svn repository"
      run: |
        cd demo/svn_server
        docker-compose run svn svnadmin create my_project_svn_repo
    - name: "Make the project svn repository writable"
      run: |
        cd demo/svn_server
        docker-compose run svn sh -c "cd /var/opt/svn/my_project_svn_repo/conf && echo '[general]
        anon-access = write' >> svnserve.conf"
    - name: "Run the svn server in the background"
      run: |
        cd demo/svn_server
        docker-compose up --detach svn
    - name: "Import test file into the project svn repository"
      run: |
        cd demo/svn_server/my_project_svn_repo
        svn import svn://localhost/my_project_svn_repo -m "initial import"
    - name: "Create meta-project svn repository"
      run: |
        cd demo/svn_server
        docker-compose run svn svnadmin create my_meta_project_svn_repo
    - name: "Make the meta-project svn repository writable"
      run: |
        cd demo/svn_server
        docker-compose run svn sh -c "cd /var/opt/svn/my_meta_project_svn_repo/conf && echo '[general]
        anon-access = write' >> svnserve.conf"
    - name: "Import an empty projects folder into the meta-project repository"
      run: |
        mkdir my_meta_project_svn_repo
        cd my_meta_project_svn_repo
        mkdir projects
        svn import svn://localhost/my_meta_project_svn_repo -m "initial import of an empty projects folder"
    - name: "Svn checkout the meta project"
      run: |
        rm -rf my_meta_project_svn_repo
        mkdir my_meta_project_svn_repo
        cd my_meta_project_svn_repo
        svn co svn://localhost/my_meta_project_svn_repo .
    - name: "Add project svn repository as svn external for the meta-project repository"
      run: |
        cd my_meta_project_svn_repo
        svn propset svn:externals "my_project_svn_repo svn://localhost/my_project_svn_repo" projects
        svn commit -m "linking projects/my_project_svn_repo as svn external"
        svn update
    - name: "Add public github repository as svn external for the meta-project repository"
      run: |
        cd my_meta_project_svn_repo
        svn propset svn:externals "my_project_svn_repo svn://localhost/my_project_svn_repo
        clsim https://github.com/claudiok/clsim.git/trunk" projects
        svn commit -m "linking projects/clsim as svn external to a public github repo"
        svn update
    - name: "Cache svn credentials for github.com"
      run: |
        svn ls --username $GITHUB_USERNAME --password $GITHUB_ACCESS_TOKEN https://github.com/IceCube-SPNO/IceTrayCombo.git/trunk
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
    - name: "Add a private github repository's folder as svn external for the meta-project repository"
      run: |
        cd my_meta_project_svn_repo
        svn propset svn:externals "my_project_svn_repo svn://localhost/my_project_svn_repo
        clsim https://github.com/claudiok/clsim.git/trunk
        monopole-generator https://github.com/IceCube-SPNO/IceTrayCombo.git/trunk/monopole-generator" projects
        svn commit -m "linking projects/monopole-generator as svn external to a private github-repo folder"
        svn update
    - name: "Svn checkout the meta-project repository and see if the external project is there"
      run: |
        rm -rf my_meta_project_svn_repo
        mkdir my_meta_project_svn_repo
        cd my_meta_project_svn_repo
        svn co svn://localhost/my_meta_project_svn_repo .
        ls projects/my_project_svn_repo
        ls projects/clsim
        ls projects/monopole-generator
