name: Tests

on: [push]

jobs:

  test_svn_externals:
    # https://github.com/fiedl/icecube-git-migration/issues/2

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Create project svn repository"
      run: |
        cd demo/svn_server
        docker-compose run svn svnadmin create my_project_svn_repo
    - name: "Make the project svn repository writable"
      run: |
        cd demo/svn_server
        docker-compose run svn sh -c "cd /var/opt/svn/my_project_svn_repo/conf && echo '[general]
        anon-access = write' >> svnserve.conf"
    - name: "Run the svn server in the background"
      run: |
        cd demo/svn_server
        docker-compose up --detach svn
    - name: "Import test file into the project svn repository"
      run: |
        cd demo/svn_server/my_project_svn_repo
        svn import svn://localhost/my_project_svn_repo -m "initial import"
    - name: "Create meta-project svn repository"
      run: |
        cd demo/svn_server
        docker-compose run svn svnadmin create my_meta_project_svn_repo
    - name: "Add svn externals for the meta-project repository"
      run: echo "pending"
    - name: "Svn checkout the meta-project repository"
      run: echo "pending"
